import pytest
from datetime import datetime
from fastapi.testclient import TestClient
from jose import jwt
from src.app import app
from src.core.config import get_settings
from src.core.security import _normalize_role, decode_token, CurrentUser
from fastapi.security import HTTPAuthorizationCredentials

client = TestClient(app)
settings = get_settings()


def create_token(payload: dict) -> str:
    return jwt.encode(payload, settings.jwt_secret, algorithm=settings.jwt_algorithm)


def test_config_reads_jwt_accesstoken():
    assert settings.jwt_secret is not None
    assert len(settings.jwt_secret) > 0
    assert settings.jwt_algorithm == "HS256"


def test_normalize_role():
    assert _normalize_role("super_admin") == "admin"
    assert _normalize_role("chuyen_vien") == "admin"
    assert _normalize_role("admin") == "admin"
    assert _normalize_role("thi_sinh") == "thi_sinh"
    assert _normalize_role("unknown_role") is None
    assert _normalize_role(None) is None


def test_decode_token_super_admin():
    token = create_token({
        "role": "super_admin",
        "ma_admin": "adm-001",
        "sub": "adm-001",
    })
    creds = HTTPAuthorizationCredentials(scheme="Bearer", credentials=token)
    user = decode_token(creds)
    assert user.role == "admin"
    assert user.admin_role == "super_admin"
    assert user.ma_admin == "adm-001"


def test_decode_token_chuyen_vien():
    token = create_token({
        "role": "chuyen_vien",
        "ma_admin": "adm-002",
        "sub": "adm-002",
    })
    creds = HTTPAuthorizationCredentials(scheme="Bearer", credentials=token)
    user = decode_token(creds)
    assert user.role == "admin"
    assert user.admin_role == "chuyen_vien"
    assert user.ma_admin == "adm-002"


def test_decode_token_fe_format_with_userid():
    # FE token format generated by SignJWT({ userId }):
    token = create_token({
        "userId": "adm-fe-123",
        "sub": "adm-fe-123",
    })
    creds = HTTPAuthorizationCredentials(scheme="Bearer", credentials=token)
    user = decode_token(creds)
    assert user.role == "admin"
    assert user.ma_admin == "adm-fe-123"


def test_ho_so_requires_admin_token():
    # Missing token -> 401
    resp = client.get("/ho-so")
    assert resp.status_code == 401
    assert "token" in resp.json().get("detail", "").lower()

    # Invalid token -> 401
    resp = client.get("/ho-so", headers={"Authorization": "Bearer invalid_token_123"})
    assert resp.status_code == 401

    # Thi sinh token -> 403 Forbidden
    student_token = create_token({"role": "thi_sinh", "cccd": "012345678901"})
    resp = client.get("/ho-so", headers={"Authorization": f"Bearer {student_token}"})
    assert resp.status_code == 403

    # Admin token -> Accepted (passes security check, status is 200 or DB response)
    admin_token = create_token({"role": "super_admin", "ma_admin": "adm-001"})
    resp = client.get("/ho-so", headers={"Authorization": f"Bearer {admin_token}"})
    assert resp.status_code in {200, 500}  # 200 if DB reachable, not 401/403


def test_dgnl_nop_does_not_require_jwt():
    # Calling POST /diem/dgnl without Authorization header
    resp = client.post(
        "/diem/dgnl",
        json={
            "cccd": "999999999999",
            "diem": 110.5,
            "ngay_cap": datetime.now().isoformat(),
            "file_dinh_kem": "https://storage.example.com/dgnl.pdf",
        },
    )
    # Must NOT return 401 Unauthorized (JWT check removed)
    assert resp.status_code != 401
    # Returns 400 because CCCD does not exist in DB, proving it passed auth and reached service validation!
    assert resp.status_code in {400, 422}
